# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-02 07:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190201_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2019, 2, 2, 7, 27, 39, 807109, tzinfo=utc)),
        ),
    ]
